config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  get '/pricing', to: 'static_pages#pricing'
  get '/signup', to: 'users#new'
  get '/about', to: 'static_pages#about'
  get '/resend_activation', to: 'users#new_activation'
  post '/resend_activation', to: 'users#resend_activation'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :subscriptions do
    member do
      get :cancel
      get :update_payment
      get :change_plan
    end
  end

  namespace :chargify do
  	resources :webhooks, only: :create
  end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
	belongs_to :user
	validates :chargify_id, presence: true
	validates :user_id, presence: true
	validates :state, presence: true

	def cancel_local_subscription 
		update_attributes(state: "canceled")
	end

	
end

app/controllers/subscriptions_controller.rb
#include UsersHelper?
#include ChargifyHelper?

class SubscriptionsController < ApplicationController

	include UsersHelper
	include ChargifyHelper

	#before_filter :redirect_private_pages?

	def show
		@user = User.find(params[:id])
		@subscription = @user.subscriptions.first
    	redirect_private_pages(@user)
	end

	def cancel
		@user = User.find(params[:id])
		@subscription = @user.subscriptions.first
		redirect_private_pages(@user)
	end

	def update_payment

	end

	def change_plan

	end

	def update
		@user = User.find(params[:id])
		@subscription = @user.subscriptions.first
		configure_chargify
		sub = Chargify::Subscription.find(@subscription.chargify_id)

		#This doesn't prevent users from logging in again 
		if params[:commit] == 'Cancel now'
			sub.cancel
			@subscription.cancel_local_subscription
			log_out
			redirect_to signup_path
			flash[:success] = "Your subscription has been canceled."

		elsif params[:commit] == 'Cancel later'
			sub.delayed_cancel
			flash.now[:success] = "Your subscription will cancel soon."
			render 'show'
		end
	end

end

app/views/subscriptions/cancel.html.erb
<% provide(:title, "Cancel Your Subscription") %>
<div class="row">
	<aside class="col-md-8">
		<section class="cancel">
			<h1>Cancel Your Subscription</h1>
			<p>Would you like to cancel your subscription? You will no longer be billed, but you will not have access to Twötter.</p>
			<p>You can choose to cancel and lose access immediately; or to keep access until your next billing period, at which point the account will close without an additional bill.</p>
			
			<%= form_for(@subscription) do |f| %>
			<%= f.submit 'Cancel now', class: "btn" %>
			<%= f.submit 'Cancel later', class: "btn" %>
			<% end %>
		</section>
	</aside>
</div>

app/views/subscriptions/show.html.erb
<% provide(:title, "Your Subscription") %>
<div class="row">
	<aside class="col-md-4">
		<section class="subscription_info">
			<h1>
				Your Subscription
			</h1>
			<p>Your name is <%= @user.name %></p>
			<p>Your Chargify subscription ID is <%= @subscription.chargify_id %></p>
		</section>
		<section class="subscription_actions">
			<p>What would you like to do?</p>
			<ul id="buttons">
				<li><%= link_to "Cancel my subscription", cancel_subscription_path %></li>
				<li><%= link_to "Update my card", update_payment_subscription_path %></li>
				<li><%= link_to "Change my plan", change_plan_subscription_path %></li>
			</ul>
		</section>
	</aside>
</div>

app/views/subscriptions/update_payment.html.erb
<html>
  <head>
    <title>Chargify</title>

    <script src="https://js.chargify.com/latest/chargify.js"></script>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
    <h1>Chargify</h1>

    <form class="host-form" id='host-form'>
      <div id="chargify1"></div>

      <div id="chargify2"></div>

      <div id="chargify3"></div>
      
      <div id="chargify4"></div>

      <div id="chargify5"></div>

      Hidden Token: <input id="host-token" disabled />

      <button type="submit" class="host-button">Submit Host Form</button>
    </form>

    <a href="http://railsapps.github.io/rails-javascript-include-external.html">Rails JS guide</a>

    <script src="app/assets/javascripts/load.js"></script>
    <script src="app/assets/javascripts/submit.js"></script>
  </body>
</html>